### ISSUE TITLE
Create "Set Undercover" module

### ISSUE THREAD

**Issue by BojanOnTheInternet** [7Cav/7Cav_FullSpectrum_V4.Altis#172]

**Comment by Robot-Panda15** [comment]
?

**Comment by BojanOro** [comment]
> ?

A few days ago there was an MCC that tried to have players infiltrate a town as "civilians" and kidnap a high ranking officer. The mission was plagued with technical difficulties because the change side function in Achilles sucks. This will be a simple zeus module that will allows MCC makers accomplish the same "undercover" effect without having to change teams.

Works similar to the "Set Captive" function, except it won't handcuff a person, just make them uninteresting to enemy AI until it's disabled.

**Comment by BojanOnTheInternet** [comment]
> ?

A little while ago there was an MCC where players move into a town as "civilians" and have to kidnap a high ranking officer. They were supposed to go in with weapons stowed and act normal but the MCC was filled with technical difficulties. This is a simple zeus module that will make players uninteresting to the enemy AI, but not switch their teams.
