### ISSUE TITLE
Apollo "Packup" option

### ISSUE THREAD

**Issue by Kalthramis** [7Cav/7Cav_FullSpectrum_V4.Altis#207]
Include an option to Apollo's FOB vic to 'pack up' all fortifications. That is, delete and refund any nearby Apollo-placed fortifications.
Potentially, also load up any nearby statics/crates into the vic, or into the repair vic (if its nearby).

This will require interfacing with `ACEX/addons/fortify/`.

**Comment by BojanOnTheInternet** [comment]
Not too sure about this feature, the tear down time is already pretty short for Apollo. I think this makes it too arcady/easy for them. Instead of making things easier for Apollo in an attempt to make their lives better/more fun, we should be making it worthwhile to setup FOBs by adding features, not simplifying gameplay.
